### PR TITLE
general tidy during PSMR workshop

### PR DESCRIPTION
**Pull request by casperdcl**
- [x] don't use reserver python names (`iter`, `slice`)
- [x] avoid extraneous spaces & semicolons
- [x] change mentions of spyder -> Jupyter
- [x] better/consistent `%matplotlib`
- [x] misc formatting
- [ ] remove "you may have to close Figure" messages when in Jupyter?
- [ ] add Jupyter widget to scroll through image slices?
- [ ] sync changes to other files not used during the workshop?

### CODE REVIEW

**Comment by KrisThielemans** [comment]
>  remove "you may have to close Figure" messages when in Jupyter?

yes, I think that would make sense

> add Jupyter widget to scroll through image slices?

I prefer to keep the python stuff really simple. we could maybe have one extra notebook with a fancy display thing.

> sync changes to other files not used during the workshop?

not sure what you mean. Other notebooks in this repo? We should have a look at them if they really make sense.

**Comment by casperdcl** [comment]
> I prefer to keep the python stuff really simple.

Does this include redefining an `imshow` function in every single notebook? Surely at least import it from a file in the same directory...

> Other notebooks in this repo?

Yes

**Comment by KrisThielemans** [comment]
> Does this include redefining an imshow function in every single notebook? Surely at least import it from a file in the same directory...

:-; `imshow` definition can probably be replaced by `show_2D_array`

**Comment by casperdcl** [comment]
think can sort out other minor things unfixed by this PR in a different issue...

**Comment by KrisThielemans** [comment]
not sure why there's a conflict, but feel free to resolve and merge :-)

**Pull request merged**
